# backend/rag_pipeline.py
"""
RAG 核心流程：文档加载 → 分块 → 向量化 → 检索
"""
import os
import numpy as np
import streamlit as st
from sklearn.metrics.pairwise import cosine_similarity
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer
from openai import OpenAI

# ===========================================
# 🔧 可配置参数
# ===========================================
USE_OPENAI_EMBEDDING = True   # 改为 True 则使用 OpenAI embedding
CHUNK_SIZE = 500
CHUNK_OVERLAP = 100
EMBED_DIM = 384   # all-MiniLM-L6-v2 输出维度
# ===========================================

# ✅ 模型初始化
if USE_OPENAI_EMBEDDING:
    client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])
    def embed_texts(texts):
        resp = client.embeddings.create(
            input=texts,
            model="text-embedding-3-small"
        )
        return np.array([d.embedding for d in resp.data])
else:
    embedder = SentenceTransformer('all-MiniLM-L6-v2')
    def embed_texts(texts):
        return embedder.encode(texts, convert_to_numpy=True, normalize_embeddings=True)

# ===========================================
# 🧩 全局存储
# ===========================================
VEC_STORE = {
    "texts": [],
    "embeddings": None
}

# ===========================================
# 📄 文本分块（改进策略）
# ===========================================
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP,
    separators=[".", "!", "?", "\n\n", "\n", " "],
)

def extract_text_from_pdf(file_obj):
    import fitz
    file_obj.seek(0)
    text = ""
    with fitz.open(stream=file_obj.read(), filetype="pdf") as doc:
        for page in doc:
            text += page.get_text()
    return text.strip()

# ===========================================
# 🚀 构建知识库
# ===========================================
def add_document_from_file(raw_text, file_type="txt"):
    from backend.embeddings import is_fitted  # 可保留原结构
    text = extract_text_from_pdf(raw_text) if file_type == "pdf" else raw_text.strip()
    if not text:
        raise ValueError("❌ No text extracted from document.")
    chunks = text_splitter.split_text(text)
    print(f"[INFO] 文本分块完成，共 {len(chunks)} 段")

    VEC_STORE["texts"] = chunks
    VEC_STORE["embeddings"] = embed_texts(chunks)
    print(f"[INFO] 向量化完成，形状 {VEC_STORE['embeddings'].shape}")

def query_rag(question: str, top_k=8):
    """
    RAG 检索 + 生成：
    从 VEC_STORE 中检索最相关的文本片段，然后用 LLM 生成回答。
    """

    texts = VEC_STORE.get("texts")
    embeddings = VEC_STORE.get("embeddings")

    # 1️⃣ 如果当前向量库里完全没有东西，就提示“无知识库”
    if not texts or embeddings is None or len(texts) == 0:
        return (
            "📭 No knowledge base available.\n\n"
            "Please upload a contract OR ask your landlord to upload a house knowledge base."
        )

    # 2️⃣ 对问题做 embedding
    q_emb = embed_texts([question])
    sims = cosine_similarity(q_emb, embeddings)[0]
    top_idx = np.argsort(sims)[-top_k:][::-1]
    context = "\n\n".join([texts[i] for i in top_idx])

    # 3️⃣ 构造 prompt
    prompt = f"""
    You are an intelligent rental & contract assistant. 
    Your task is to answer the user's question using the provided context. 

    Follow these rules:

    1. **If the question asks for a summary, overview, outline, key points, main ideas, or general description**, 
    then generate a high-quality summary *based on the context*, even if it does not explicitly contain headings.

    2. **If the question is factual (dates, responsibilities, clauses, fees, etc.)**, 
    answer ONLY using information found in the context. Do not fabricate missing facts.

    3. **If the context does not contain the required factual information**, 
    respond naturally:  
    “The provided documents do not mention this information.”

    4. **Do NOT mention that you used a knowledge base. Do NOT show the context.**

    <context>
    {context}
    </context>

    <question>
    {question}
    </question>

    Provide the best possible answer:
    """


    if USE_OPENAI_EMBEDDING:
        client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])
        resp = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "You are a professional contract Q&A assistant."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            max_tokens=512,
        )
        return resp.choices[0].message.content.strip()
    else:
        # 不调用 LLM 时，直接把检索结果返回
        return (
            "📄 Most relevant context:\n\n"
            + context[:800]
            + "\n\n(A final answer should be generated by a language model based on the retrieved context)"
        )


# ===========================================
# ✅ 工具函数
# ===========================================
def is_fitted():
    return VEC_STORE["embeddings"] is not None
