# backend/rag_pipeline.py
"""
RAG 核心流程：文档加载 → 分块 → 向量化 → 检索
"""
import os
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer
from openai import OpenAI

# ===========================================
# 🔧 可配置参数
# ===========================================
USE_OPENAI_EMBEDDING = True   # 改为 True 则使用 OpenAI embedding
CHUNK_SIZE = 500
CHUNK_OVERLAP = 100
EMBED_DIM = 384   # all-MiniLM-L6-v2 输出维度
# ===========================================

# ✅ 模型初始化
if USE_OPENAI_EMBEDDING:
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    def embed_texts(texts):
        resp = client.embeddings.create(
            input=texts,
            model="text-embedding-3-small"
        )
        return np.array([d.embedding for d in resp.data])
else:
    embedder = SentenceTransformer('all-MiniLM-L6-v2')
    def embed_texts(texts):
        return embedder.encode(texts, convert_to_numpy=True, normalize_embeddings=True)

# ===========================================
# 🧩 全局存储
# ===========================================
VEC_STORE = {
    "texts": [],
    "embeddings": None
}

# ===========================================
# 📄 文本分块（改进策略）
# ===========================================
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP,
    separators=[".", "!", "?", "\n\n", "\n", " "],
)

def extract_text_from_pdf(file_obj):
    import fitz
    file_obj.seek(0)
    text = ""
    with fitz.open(stream=file_obj.read(), filetype="pdf") as doc:
        for page in doc:
            text += page.get_text()
    return text.strip()

# ===========================================
# 🚀 构建知识库
# ===========================================
def add_document_from_file(raw_text, file_type="txt"):
    from backend.embeddings import is_fitted  # 可保留原结构
    text = extract_text_from_pdf(raw_text) if file_type == "pdf" else raw_text.strip()
    if not text:
        raise ValueError("❌ No text extracted from document.")
    chunks = text_splitter.split_text(text)
    print(f"[INFO] 文本分块完成，共 {len(chunks)} 段")

    VEC_STORE["texts"] = chunks
    VEC_STORE["embeddings"] = embed_texts(chunks)
    print(f"[INFO] 向量化完成，形状 {VEC_STORE['embeddings'].shape}")

# ===========================================
# 🔍 检索 + 生成
# ===========================================
def query_rag(question: str, top_k=8):
    if VEC_STORE["embeddings"] is None:
        return "❌ Please first upload and index the"

    q_emb = embed_texts([question])
    sims = cosine_similarity(q_emb, VEC_STORE["embeddings"])[0]
    top_idx = np.argsort(sims)[-top_k:][::-1]
    context = "\n\n".join([VEC_STORE["texts"][i] for i in top_idx])

    # 🔹 生成回答
    # 🔹 Generate response
    prompt = f"""
You are an intelligent contract assistant. Please answer the question based on the following context. Do not fabricate information.

<context>
{context}
</context>

<question>
{question}
</question>

<answer>
"""
    if USE_OPENAI_EMBEDDING:
        client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        resp = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "You are a professional contract Q&A assistant."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.3,
            max_tokens=512
        )
        return resp.choices[0].message.content.strip()
    else:
        # 🔹 If not connecting to OpenAI for now, return retrieval result instead
        return f"📄 Most relevant context:\n\n{context[:800]}...\n\n(A final answer should be generated by a language model based on the retrieved context)"

# ===========================================
# ✅ 工具函数
# ===========================================
def is_fitted():
    return VEC_STORE["embeddings"] is not None
